#python 3.7.)
import os,sys,time
os.system("clear")
def chk():
           print("[✓]installing... :) ")
time.sleep(15)
os.system("termux-setup-storage")
time.sleep(5)
os.system("pkg update")
os.syestem("pkg upgrade")
os.syestem("clear")
os.system("pkg install python -y")
os.system("clear")
os.system("pkg install python2 -y")
os.system("clear")
os.system("pkg install git -y")
os.system("clear")
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install nano -y ")
os.system("clear")
os.system("pip install mechanize")
os.system("clear")
os.system("pip2 install mechanize")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip2 install requests")
os.system("clear")
os.system("pkg install mpv -y")
os.system("clear")
os.system("pip install wget")
os.system("clear")
os.system("pkg install ruby -y")
os.system("clear")
os.system("pkg install php -y")
os.system("clear")
os.system("pip install tools")
os.system("clear")
os.system("pkg install bash -y")
os.system("clear")
os.system("pkg Install nmap -y")
os.system("clear")
os.system("pkg install SETAN -y")
os.system("clear")
os.system("pkg install nodejs -y")
os.system("clear")
os.system("pkg install golang")
os.system("clear")
os.system("pkg install cowsay")
os.system("clear")
os.system("pip2 install mechanize")
os.system("clear")
os.system("pip install telethon")
os.system("clear")
os.system("pip inatall phonenumbers")
os.system("clear")
os.system("pkg install o-editor -y")
os.system("clear")
os.system("apt install dnsutils -y")
os.system("clear")
os.system("apt Install Nmap -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg intsall nano -y")
os.system("clear")
os.system("pkg install openssl-tool -y")
os.system("clear")
os.system("pkg install curl -y")
os.system("clear")
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install unzip -y")
os.system("clear")
os.system("pkg install zip -y")
os.system("clear")
os.system("pkg install sl -y")
os.system("clear")
os.system("pkg install tor -y")
os.system("clear")
os.system("pkg install wget")
os.system("clear")
os.system("pkg install gogle -y")
os.system("clear")
os.system("pkg install cmatrix -y")
os.system("clear")
os.system("pip install colorama ")
os.system("clear")
os.system("pip install --upgrade pip")
os.system("clear")
os.system("figlet Tawaw")